#!/usr/bin/env bash
#This script configures an HAProxy of version 1.7
sudo apt-get install software-properties-common
echo | sudo add-apt-repository ppa:vbernat/haproxy-1.7
sudo apt update
sudo apt install -y haproxy
my_string="\nfrontend http_front\n\tbind *:80\n\tstats uri /haproxy?stats\n\tdefault_backend http_back\n\nbackend http_back\n\tbalance roundrobin\n\tserver 252-web-01 54.86.111.122:80 check\n\tserver 252-web-02 34.228.26.238:80 check\n"
echo -e "$my_string" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
