#!/usr/bin/env bash
#This script configures an HAProxy of version 1.7
echo | sudo add-apt-repository ppa:vbernat/haproxy-1.7
sudo apt update
sudo apt install -y haproxy
frontend_string="\nfrontend http_front\n\tbind *:80\n\tstats uri /haproxy?stats\n\tdefault_backend http_back\n"
backend_string="\nbackend http_back\n\tbalance roundrobin\n\tserver 252-web-01 54.86.111.122:80 check\n\tserver 252-web-02 34.228.26.238:80 check\n"
echo -e "$frontend_string" | sudo tee /etc/haproxy/haproxy.cfg
echo -e "$backend_string" | sudo tee /etc/haproxy/haproxy.cfg
sudo systemctl restart haproxy
