#!/usr/bin/env bash
# script that generates a MySQL dump and creates a compressed archive out of it
mysqldump --all-databases --password="$1" --user=root > backup.sql
tar czvf "$(date '+%d-%m-%Y').tar.gz" backup.sql
