#!/usr/bin/env bash
# This script displays numbers 1 to 100 using Fizzbuzz idea
for ((i=1;i<101;i++))
{
    if ((i % 15 == 0)); then echo "FizzBuzz"
    elif ((i % 5 == 0)); then echo "Buzz"
    elif ((i % 3 == 0)); then echo "Fizz"
    else echo $i
    fi
}
exit 0
