#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
count=0
while [ $count -le 10 ]
do
    echo "Holberton School"
    if [ $count -eq 9 ]; then
	break
    fi
    (( count++ ))
done
