#!/usr/bin/env bash
# This script displays bad luck @ 4, good luck @ 8
count=1
while [ $count -le 10 ]
do
    if [ $count -eq 4 ]; then echo "bad luck"
    elif [ $count -eq 8 ]; then echo "good luck"
    else echo "Holberton School"
    fi
    (( count++ ))
done
