#!/usr/bin/env bash
# Script sets up basic Nginx server with message
sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx restart
