#!/usr/bin/env bash
# Script configures server to redirect to another page
sudo apt-get -y update
sudo apt-get install -y nginx
new_string="\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\t\n\t}\n"
sed -i "38i\ $new_string" /etc/nginx/sites-available/default
sudo service nginx restart
