#!/usr/bin/env bash
#script configures container to run nginx as nginx user listening on 8080 port
sed -i "s/#user www-data;/user nginx;/" /etc/nginx/nginx.conf
sed -i "s/80/8080/" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
chown -R nginx:nginx /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx /usr/sbin/service nginx start
